// <auto-generated />
using System;
using BangumiProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BangumiProject.Migrations.MoeMushi
{
    [DbContext(typeof(MoeMushiContext))]
    [Migration("20181230111055_Mushi00")]
    partial class Mushi00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("BangumiProject.Process.MoeMushi.Model.AnimeInfoSea", b =>
                {
                    b.Property<int>("DBID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Aid");

                    b.Property<int>("AnimeNum");

                    b.Property<int>("Cid");

                    b.Property<string>("Cover");

                    b.Property<int>("Id");

                    b.Property<string>("Long_title");

                    b.Property<int>("Season_id");

                    b.Property<string>("Share_url");

                    b.Property<int>("Stat_play");

                    b.Property<string>("Title");

                    b.HasKey("DBID");

                    b.ToTable("AnimeInfoSeas");
                });

            modelBuilder.Entity("BangumiProject.Process.MoeMushi.Model.TimeLineInfo", b =>
                {
                    b.Property<int>("DBID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cover");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("Delay");

                    b.Property<string>("Delay_index");

                    b.Property<string>("Delay_reason");

                    b.Property<int>("Ep_id");

                    b.Property<int>("Favorites");

                    b.Property<bool>("Is_published");

                    b.Property<string>("Pub_index");

                    b.Property<string>("Pub_time");

                    b.Property<int>("Season_id");

                    b.Property<string>("Square_cover");

                    b.Property<string>("Title");

                    b.HasKey("DBID");

                    b.ToTable("TimeLines");
                });

            modelBuilder.Entity("BangumiProject.Process.MoeMushi.Model._LogInfo", b =>
                {
                    b.Property<int>("INFOID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.Property<DateTime>("Time");

                    b.HasKey("INFOID");

                    b.ToTable("LogInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
